bot.name: VasilievskyBot
bot.token: 6062376683:AAGo2MEutadW61gnMKR78nbga_s0QnkcYY8
bot.chatId: 6062376683

server:
  port: 8080
spring:
  datasource:
    username: root
    password: AllMightBoGdaN2003
    url: jdbc:mysql://localhost:3306/telegram_bot?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true